# Generated by Django 4.1.9 on 2023-05-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=11, verbose_name='placa')),
                ('entrada', models.DateTimeField(auto_now=True, verbose_name='Entrada veículo')),
                ('saida', models.DateTimeField(auto_now=True, verbose_name='Saída veículo')),
            ],
            options={
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('senha', models.CharField(max_length=150, verbose_name='senha')),
                ('permissao', models.IntegerField(verbose_name='permissao')),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=11, verbose_name='placa')),
                ('tipo', models.CharField(max_length=30, verbose_name='tipo')),
                ('marca', models.CharField(max_length=30, verbose_name='marca')),
                ('modelo', models.CharField(max_length=30, verbose_name='modelo')),
                ('cor', models.CharField(max_length=30, verbose_name='cor')),
                ('proprietario', models.CharField(max_length=150, verbose_name='proprietario')),
                ('cpf_proprietario', models.IntegerField(max_length=11, verbose_name='cpf_proprietario')),
                ('telefone', models.IntegerField(max_length=11, verbose_name='telefone')),
            ],
        ),
    ]
