# Generated by Django 3.2.19 on 2023-06-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculomodel',
            name='status',
            field=models.CharField(default='Não Estacionado', max_length=20, verbose_name='status'),
        ),
    ]
