# Generated by Django 3.2.19 on 2023-06-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_veiculomodel_cpf_proprietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculomodel',
            name='status',
            field=models.CharField(default='Não Estacionado', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='veiculomodel',
            name='cpf_proprietario',
            field=models.CharField(max_length=11, verbose_name='cpf_proprietario'),
        ),
        migrations.AlterField(
            model_name='veiculomodel',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='telefone'),
        ),
    ]
