# Generated by Django 3.2.19 on 2023-06-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculomodel_status'),
        ('core', '0003_auto_20230604_2007'),
    ]

    operations = [
    ]
